version: "3"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./ssl/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-le
        depends_on:
        - nginx-proxy
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
            - DEFAULT_EMAIL=$EMAIL
        volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./ssl/dhparam.pem:/etc/nginx/dhparam/dhparam.pem
        - vhost:/etc/nginx/vhost.d
        - certs:/etc/nginx/certs
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    vhost:
    html:
    certs:

networks:
    default:
        external:
            name: nginx-proxy